### ISSUE TITLE
how to run the project

### ISSUE THREAD

**Issue by aycanvargun** [ctron/kapua-gateway-client#6]
Hi, 

I have built the project successfully. I want to create and run a Kura client. I didn't understand how to run and use the project.  I have  kapua-gateway-client-profile-kura-0.2.2-SNAPSHOT.jar  file. And i tried these to run from my gitbash: 

java -cp /target/kapua-gateway-client-profile-kura-0.2.2-SNAPSHOT.jar  src.test.java.org.eclipse.kapua.gateway.client.KuraExample

java -cp /target/kapua-gateway-client-profile-kura-0.2.2-SNAPSHOT.jar  test-classes.org.eclipse.kapua.gateway.client.KuraExample

Could you please help me about how to run and use the project after building

**Comment by ctron** [comment]
I would suggest to create a new project, and simply start with the example client: https://github.com/ctron/kapua-gateway-client/blob/master/README.md#example-client

You don't need to re-build the gateway client projects, as they are available from Maven Central: https://github.com/ctron/kapua-gateway-client/blob/master/README.md#add-to-your-maven-project

**Comment by aycanvargun** [comment]
I have solved by creating a new maven project and adding the dependencies to my POM. Thank you.
